### ISSUE TITLE
Not able to install from github

### ISSUE THREAD

**Issue by skyjur** [analytics-pros/universal-analytics-python#20]
Doing
```
$ pip install -e git+https://github.com/analytics-pros/universal-analytics-python.git#egg=universal-analytics-python-dev
Obtaining universal-analytics-python from git+https://github.com/analytics-pros/universal-analytics-python.git#egg=universal-analytics-python-dev
  Cloning https://github.com/analytics-pros/universal-analytics-python.git to ./env/src/universal-analytics-python
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "env/src/universal-analytics-python/setup.py", line 4, in <module>
        VERSION=open('commit-version').read().strip()
    IOError: [Errno 2] No such file or directory: 'commit-version'
```
throws
```
IOError: [Errno 2] No such file or directory: 'commit-version'
```
I can see that in `setup.py` it tries to open `commit-version` file which is missing
https://github.com/analytics-pros/universal-analytics-python/blob/master/setup.py#L4

**Comment by ronalddas** [comment]
even, i was getting the same error. but `pip install universal-analytics-python` worked.
Although, it looks the library is not working anymore, couldn't see any change in my analytics page even after trying the example mentioned in the readme
