### ISSUE TITLE
I cannot install this pip package

### ISSUE THREAD

**Issue by pupeno** [analytics-pros/universal-analytics-python#21]
It fails with this error:

```
C:\Users\pupeno\...> pip install universal-analytics-python
Collecting universal-analytics-python
  Using cached https://files.pythonhosted.org/packages/83/15/6d499f1f6a1ef85574da9b32196beb1f12095ef4e2d425d74c35d734f67c/universal-analytics-python-0.2.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\pupeno\AppData\Local\Temp\pip-install-rw2fjv0p\universal-analytics-python\setup.py", line 5, in <module>
        print >>sys.stderr, "Preparing version {0}\n".format(VERSION or "NOTFOUND")
    TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'. Did you mean "print(<message>, file=<output_stream>)"?

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\pupeno\AppData\Local\Temp\pip-install-rw2fjv0p\universal-analytics-python\

```

**Comment by DmytroLitvinov** [comment]
Hello @pupeno ,

I think you are trying to install with Python3. This library is not compatible with Python3.
